### ISSUE TITLE
goblin.exception.GremlinServerError: 500: The provided key/value array length must be a multiple of two

### ISSUE THREAD

**Issue by blackthorne** [davebshow/goblin#21]
Examples from documentation won't work with latest TP3 as addV() is expecting an even number of arguments.

Instead of:
    resp = await g.addV('developer').property('name', 'Leif').next()

You need something like:
    resp = await g.addV('person','developer').property('name', 'Leif').next()

OGM examples ( session.add() ) seem to break for the very same reason.

Kind regards,
Francisco

**Comment by leifurhauks** [comment]
Hi Francisco, thanks for your feedback! Are you using TinkerPop 3.0? I've just been looking into this and it seems that a new API was added for the `addV` step in tp3.1, but that the old one is still supported.

The new API is the one of the form `g.addV('developer').property('name', 'Leif')`, while the old one has an even number of parameters because the label and any other properties are all defined as parameters on the `addV` step, like this: `g.addV(T.label, 'developer', 'name', 'Leif')`. If you're using TinkerPop 3.0 you will need to use the older API in raw gremlin queries; and I think we can patch the OGM so that vertices can be added with tp3.0.

Thanks again!

**Comment by blackthorne** [comment]
Hi Leif,
thank you for your quick reply.

I'm using TP 3.0.1, thought it was the latest one because of it's the latest version on Titan's website, where I got it from ( titan-1.0.0-hadoop1.zip ). I'm completely new on this, what setup would you recommend?

Kind regards,
Francisco

**Comment by davebshow** [comment]
Hi Francisco,

Thanks for your interest in Goblin, If you want to use Titan, I would suggest using Titan 1.1, but you will have to build it from the source contained in the Github repo, instructions for doing so can be found here: https://github.com/thinkaurelius/titan/blob/titan11/titan-dist/README.md.

However, depending on your use case, I would also recommend checking out DataStax Enterprise Graph, which looks to be the next big thing in distributed graph computing.

Best,

Dave

**Comment by blackthorne** [comment]
Thank you so much, happy days!

May I ask what would be right place to ask general questions about goblin?

(Please feel free to close this ticket)

**Comment by davebshow** [comment]
Sure, you can discuss on gitter: https://gitter.im/ZEROFAIL/goblin
