### ISSUE TITLE
Task was destroyed but it is pending

### ISSUE THREAD

**Issue by patricknee** [davebshow/goblin#42]
I am new to async/await.

On my development machine my async / await code seems to work perfectly (running on a quite slow ssh connection). When moved to a testing machine in AWS (and running against the same titan server in AWS, both machines running python 3.5.2, dev=Mac, test=Ubuntu 16) I am getting the following errors:

```
Task was destroyed but it is pending!
task: <Task pending coro=<Connection._terminate_response() running at /usr/local/lib/python3.5/site-packages/goblin/driver/connection.py:251> wait_for=<Future pending cb=[Task._wakeup()]>>
```

This seems to be occurring in the following command run_titan_cmd, which is based on the Goblin docs. Any hints? Is it returning the msg before the response termination is complete?

```
    async def run_titan_cmd(self, script, binding):
            conn = await driver.Connection.open( 'ws://'+self.titanURI+':8182/gremlin', loop,  message_serializer=GraphSONMessageSerializer)
            async with conn:
                resp = await conn.submit(gremlin=script, bindings=binding)
                async for msg in resp:
                    return msg
```

**Comment by davebshow** [comment]
Hi @patricknee. What is happening here is that when you return the first message in the loop you are short circuiting the iteration so the response is not properly closed. Normally, the response receives `None` from the driver, closes the response, and calls `StopAsyncIteration`. However, you never get there because you just return the first result. There are two ways to avoid this:

1. If you are unsure of the number of results that will be returned in the stream, you can store them in a container until the iteration finishes:

```python
result = []
resp = await conn.submit(gremlin=script, bindings=binding)
async for msg in resp:
    result.append(msg)
return result
```

2. If you are sure that you are only going to get one result back on the stream you can do this:

```python
resp = await conn.submit(gremlin=script, bindings=binding)
result = await resp.fetch_data()
resp.close()
return result
```

However, the first approach is preferable to the second because this assures that you read all the returned results from the underlying stream. When Python 3.6 becomes generally available, you will be able to simply yield results as they come in, and this will be the best option of all:

```python
resp = await conn.submit(gremlin=script, bindings=binding)
async for msg in resp:
    yield msg
```

I hope that helps and thanks for your interest in Goblin. Let me know if you have any more questions.

**Comment by patricknee** [comment]
Yes, I was pretty sure it was the iterable nature of response, and I should have tried handling the result in a list...  I tried a few other things (appending strings) before writing. Thanks for the quick response.

**Comment by davebshow** [comment]
No worries. I'm going to go ahead and close this issue.
