### ISSUE TITLE
Gremlin Properties: The provided key/value array length must be a multiple of two

### ISSUE THREAD

**Issue by decebal** [davebshow/goblin#47]
I get this error when trying to use my models and save them:

```
[gremlin-server-exec-2] WARN  org.apache.tinkerpop.gremlin.server.op.AbstractEvalOpProcessor  - Exception processing a script on request [RequestMessage{, requestId=a686a34e-d070-4900-b36a-d9b9b953f338, op='eval', processor='', args={gremlin=g.addV("memorial").property(k0, v0), aliases={}, bindings={k0=dateOfBirth, v0=now}}}].

 java.lang.IllegalArgumentException: The provided key/value array length must be a multiple of two
```

This is my code:
```
    gigi = MyVertex()
    gigi.dateOfBirth = "now"
    gigi.verified = False

    name = Name()
    name.firstName = "Gigi"
    name.title = "Mr"

    named = KnownAs(gigi, name)

    session.add(gigi, name, named)
    await session.flush()
```

While a raw gremlin query would work:

```
    resp = await g.addV('person', 'developer').property('name', 'Leif').next()
    script = "g.addV('person','developer').property(k1, v1)"
    bindings = {'k1': 'name', 'v1': 'Leif'}

    session = await app.session()
    resp = await session.submit(gremlin=script, bindings=bindings)
```

Is there a mapping problem or is it just that properties should be a tuple ? no clue what is happening

**Comment by davebshow** [comment]
What version of Gremlin Server are you using? It looks like you are using < 3.1, which unfortunately will not work with Goblin due to API changes introduced in the 3.1 line. The reason your "raw" query works is that the `addV` thinks the args you are passing use the signature `addV(key, val)`. Really you are just passing several labels. This problem has been addressed and explained in this [issue](https://github.com/davebshow/goblin/issues/21), where I noticed that you kindly gave a thumbs down emoji. Bottom line: build Titan 1.1. Titan 1.0 barely works anyway. If you can't figure out how to build it, why don't you look around and you may find some [tips](https://github.com/davebshow/goblin/issues/28)

**Comment by decebal** [comment]
Hi @davebshow , it's not that I can't figure out how to build it, but I rely on titan working with aws 's dynamodb and it looks like they can only plugin 1.0 . I am too happy about building the image myself either, but I have no problems doing so if it would work with dynamoDb. 
If you have any suggestions about that I am happy to listen and try to change things around :dancing_men:  

Begs the question then, is there anything that I can contribute so that this would work with titan 1.0 ? 

> Titan 1.0 barely works anyway

And  what do you mean by this ? :face_with_thermometer:

**Comment by davebshow** [comment]
Well, the problem is the TinkerPop version.  3.0.x was developed during the Apache incubation phase, and major breaking changes were introduced in the 3.1 line. Goblin was developed well after 3.1 was released, and didn't target any early versions of the server. It shouldn't be too hard to set up Titan 1 to run with a newer version of the Gremlin Server, but I haven't ever done so myself. If you need advice on this, I would recommend the [Aurelius Google group](https://groups.google.com/forum/#!forum/aureliusgraphs). 

I say that Titan 1.0 barely works because about a year ago we were smoke testing a distributed system that used both goblin and Titan. We had tons of trouble with Titan under a relatively light load. Updating to 1.1 helped quite a bit, but I still wouldn't recommend putting Titan into production. The same system with Goblin and DSE worked extremely well. Have you looked into JanusGraph at all? If you are looking at using an open source graph db I would highly recommend starting there, as all development moving forward will be focused [here](https://github.com/JanusGraph/janusgraph).

**Comment by davebshow** [comment]
> Begs the question then, is there anything that I can contribute so that this would work with titan 1.0

Regarding this, no, unfortunately not. I don't want to make any changes to goblin that will make it work with old versions of TP that are not compatible with the current development line.

**Comment by davebshow** [comment]
Hi @decebal. I just stumbled across this project that may be useful for you: https://github.com/petteraas/docker-titan

**Comment by decebal** [comment]
Thanks for the link @davebshow , but now that I can't use it with dynamoDB have started to consider a plethora of other options, actually I feel a bit lost as I would still like to use an ogm like goblin, 
but I have no clue if JanusGraph is ready for production as that would seem to me the next best or if either arangodb or orientdb would allow me to connect the gremlin driver to them. 

I would love if you have any tips to share regarding this.

**Comment by davebshow** [comment]
Well I'm not sure, I think JanusGraph will be the way to go if you can hold out for a small amount of time. If you are still developing/testing your app, you can probably start working with JanusGraph right away. Also, I would keep an eye on the google groups. This thread may be of interest: https://groups.google.com/forum/#!topic/janusgraph-dev/8jkMnkKzmC0
