### ISSUE TITLE
Goblin no longer supports Titan 1.1 serialization?

### ISSUE THREAD

**Issue by oberonv1** [davebshow/goblin#50]
Just recently updated goblin to version 2.0.0. The following code used to work fine with Titan 1.1 since it was using the GraphSON1 Serializer packaged with goblin 1.0.0b:
```
eventloop = asyncio.get_event_loop()
conn = await driver.Connection.open(
             'ws://localhost:8182/gremlin', eventloop,
             message_serializer=driver.serializer.GraphSONMessageSerializer)
```

I noticed the serializer has migrated to `aiogremlin` as of 2.0.0 and tried to update the code with the following:
```
eventloop = asyncio.get_event_loop()
    cluster = await Cluster.open(
        eventloop,
        message_serializer=driver.GraphSONMessageSerializer
```

But now it seems to be hanging just like it did when using the GraphSON2 serializer that was the default for the `Connection.open` function. Is Titan 1.1 no longer officially supported?

**Comment by davebshow** [comment]
The issue here is that we decided to restructure these project so they coincide more closely with the TinkerPop release schedule. In order to provide consistent versioning, the Gremlin Language Variant and driver that were bundled with the beta releases of Goblin have been extracted to the `aiogremlin` library so that they can be regularly rebased against the official Gremlin-Python. `aiogremlin` will now follow the TinkerPop release schedule. The current TinkerPop, as well as `aiogremlin`, is in version 3.2.4. What this means is that in order to use `aiogremlin`, you must be using Gremlin Server 3.2.4 as well. GraphSON1 support is being phased out of the TinkerPop project, as GraphSON2 is stabilizing and GraphSON3 is being developed.

Therefore, to use Goblin with any version of any graph database (Titan, DSE, Neo4j, JanusGraph), you must be using the proper version of TinkerPop. Since Goblin 2.0 depends on `aiogremlin` 3.2.4, it requires Gremlin Server 3.2.4

Now, your choices here are:

1. Continue using the older version of Goblin.

2. Configure Titan to use a newer TP version.

3. (BEST OPTION) Move to JanusGraph. As far as I understand it, Titan is no longer under active development. The community of developers responsible for Titan have moved their work to JanusGraph, which is backed by the Linux foundation and developers from Google, IBM, etc.

Hopefully that is clear. I really think JanusGraph is the future, and since it is an evolution of Titan, the migration should be straightforward. Let me know if you have more questions.

**Comment by oberonv1** [comment]
Thanks for the quick reply Dave! 

I was trying to compare all the graph database options using Goblin as the main Gremlin interface. I was hoping I could compare Titan 1.1 and JanusGraph by stress testing via Goblin, but I've come to the same conclusion that JanusGraph is essentially updated and active Titan.
I'll stick to JanusGraph in the foreseeable future :) 

By any chance do you know how to use Goblin with Neo4j, specifically version 3.x or above? All the Gremlin Server plugins seem to only work with 2.x, such as [this one from what was formerly Aurelius](https://github.com/thinkaurelius/neo4j-gremlin-plugin) or [this neo4j container disclaimer](https://github.com/MrSaints/docker-gremlin-neo4j). Let me know if you happen to know anything about that, as it seems Neo4j hasn't been supporting Gremlin too well recently.

Thanks again!

**Comment by davebshow** [comment]
TBH I'm not really sure about Neo4j 3.x line and TinkerPop. The [gremlin users google group](https://groups.google.com/forum/#!forum/gremlin-users) should be a good place to get answers about this.

**Comment by davebshow** [comment]
Btw, I'm working on optimizing some quick and dirty queries that were written for Goblin 2.0, be sure to update to the newest version when released. Should be tomorrow at the latest.
