### ISSUE TITLE
grakn

### ISSUE THREAD

**Issue by ghost** [davebshow/goblin#53]
what's your thoughts on goblin + grakn.ai?

**Comment by leifurhauks** [comment]
Since it implements TinkerPop 3, Goblin could work with it in theory, but are you sure you would want to use it with Goblin? Goblin wouldn't leverage Graql or the REST API. I didn't know anything about Grakn before looking at the website today, so I don't really know what I'm talking about here, but looking at [this architecture diagram](https://grakn.ai/pages/documentation/the-fundamentals/grakn-architecture.html#grakn-engine), I get the impression that by strictly using the TinkerPop API, you would be missing out on a lot of what makes Grakn Grakn.

**Comment by haikalpribadi** [comment]
hey @pouledodue 

@leifurhauks is absolutely right. If you use the TinkerPop API to read our graph, it is possible, but you will find it extremely confusing, and you definitely won't benefit from anything we built. 

We use TinkerPop's property graph model as our **underlying data structure** to build a **knowledge representation system**. The result is that you then have a [distributed] **knowledge base** with a *reasoning query language* which Graql. Thus, without using Graql, you won't benefit from any of the inference that Graql provides to you, which then, you might as well just use a normal graph database.

**Comment by haikalpribadi** [comment]
That said, of course, I think goblin + grakn.ai would be super awesome :) if you would like to ingrate goblin with the Graql API !! :)

**Comment by davebshow** [comment]
Thanks for the replies guys. The experts have spoken. What do you think @pouledodue...?

**Comment by davebshow** [comment]
Going to close this issue. Feel free to reopen for more discussion if necessary.
